name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - apps/**
      - packages/**

jobs:
  js_code_review:
    uses: pagopa/dx/.github/workflows/js_code_review.yaml@abb37e552370c4b3e2e5b2601c76a307f421c074 # main
    name: Code Review
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write