name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    uses: pagopa/dx/.github/workflows/release-v1.yaml@723b8233cd9c48bac7cc9e796471d4e12d4f8e5c # main
    with:
      environment: app-prod-cd
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}